;/*FB_PKG_DELIM*/

__d("IGDInboxTrayQuery$Parameters",["IGDInboxTrayQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("IGDInboxTrayQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_get_inbox_tray_items"]},name:"IGDInboxTrayQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("IGDInboxTray.entrypoint",["IGDInboxTrayQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{queryReference:{parameters:c("IGDInboxTrayQuery$Parameters"),variables:{}}}}},root:c("JSResourceForInteraction")("IGDInboxTray.react").__setRef("IGDInboxTray.entrypoint")};g["default"]=a}),98);
__d("IGDInboxTrayMobileQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9452554661510978"}),null);
__d("IGDInboxTrayMobileQuery$Parameters",["IGDInboxTrayMobileQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("IGDInboxTrayMobileQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_get_inbox_tray_items"]},name:"IGDInboxTrayMobileQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("IGDInboxTrayMobile.entrypoint",["IGDInboxTrayMobileQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{queryReference:{parameters:c("IGDInboxTrayMobileQuery$Parameters"),variables:{}}}}},root:c("JSResourceForInteraction")("IGDInboxTrayMobile.react").__setRef("IGDInboxTrayMobile.entrypoint")};g["default"]=a}),98);
__d("IGDMqttIrisSubscriptionQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9476575619127164"}),null);
__d("IGDMqttIrisSubscriptionQuery$Parameters",["IGDMqttIrisSubscriptionQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("IGDMqttIrisSubscriptionQuery_instagramRelayOperation"),metadata:{},name:"IGDMqttIrisSubscriptionQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("IGDUqppSequenceIDTracker",[],(function(a,b,c,d,e,f){"use strict";a=function(){function a(){}var b=a.prototype;b.updateSequenceID=function(a){this.$1=a};b.getSequenceID=function(){return this.$1};return a}();f["default"]=a}),66);
__d("IGDUqppSequenceIDTrackerSingleton",["IGDUqppSequenceIDTracker"],(function(a,b,c,d,e,f,g){"use strict";a=new(c("IGDUqppSequenceIDTracker"))();b=a;g["default"]=b}),98);
__d("PolarisAutomaticPreviewsDisabledContextProviderQuery$Parameters",["PolarisAutomaticPreviewsDisabledContextProviderQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisAutomaticPreviewsDisabledContextProviderQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_get_igd_automatic_previews_disabled"]},name:"PolarisAutomaticPreviewsDisabledContextProviderQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisDirectInboxMobileRoot.entrypoint",["IGDInboxTrayMobile.entrypoint","IGDMqttIrisSubscriptionQuery$Parameters","IGDThreadDetailMainViewOffMsysQuery$Parameters","IGDUqppSequenceIDTrackerSingleton","IGPresenceUnifiedSetupQuery$Parameters","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","PolarisViewerSettingsQuery$Parameters","gkx","qex"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps;var e={presenceSetupQueryRef:{parameters:c("IGPresenceUnifiedSetupQuery$Parameters"),variables:{}},viewerQueryRef:{parameters:c("IGDMqttIrisSubscriptionQuery$Parameters"),variables:{}}};a.thread_fbid!=null&&a.thread_fbid!==""&&(e=babelHelpers["extends"]({},e,{threadPointQueryRef:{parameters:c("IGDThreadDetailMainViewOffMsysQuery$Parameters"),variables:{min_uq_seq_id:c("IGDUqppSequenceIDTrackerSingleton").getSequenceID(),pass_message_list_gk:c("gkx")("3912"),thread_fbid:a.thread_fbid}}}));c("qex")._("4042")===!0&&(e=babelHelpers["extends"]({},e,{viewerSettingsQueryRef:{parameters:c("PolarisViewerSettingsQuery$Parameters"),variables:{}}}));return{entryPoints:{inboxTrayEntrypointMobile:d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("IGDInboxTrayMobile.entrypoint"),entryPointParams:{}})},queries:e}},root:c("JSResourceForInteraction")("PolarisDirectInboxMobileRoot.react").__setRef("PolarisDirectInboxMobileRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisDirectInboxQPInterstitialQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"9824483370907736",metadata:{},name:"PolarisDirectInboxQPInterstitialQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisDirectInboxRoot.entrypoint",["IGDInboxTray.entrypoint","IGDMqttIrisSubscriptionQuery$Parameters","IGDThreadDetailMainViewOffMsysQuery$Parameters","IGDUqppSequenceIDTrackerSingleton","IGPresenceUnifiedSetupQuery$Parameters","JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","PolarisAutomaticPreviewsDisabledContextProviderQuery$Parameters","PolarisDirectInboxQPInterstitialQuery$Parameters","PolarisViewerSettingsQuery$Parameters","gkx","qex"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){a=a.routeProps;var e={automaticPreviewsSettingsQueryRef:{parameters:c("PolarisAutomaticPreviewsDisabledContextProviderQuery$Parameters"),variables:{}},presenceSetupQueryRef:{parameters:c("IGPresenceUnifiedSetupQuery$Parameters"),variables:{}},qpInterstitialQueryRef:{parameters:c("PolarisDirectInboxQPInterstitialQuery$Parameters"),variables:{}},viewerQueryRef:{parameters:c("IGDMqttIrisSubscriptionQuery$Parameters"),variables:{}}};a.thread_fbid!=null&&a.thread_fbid!==""&&(e=babelHelpers["extends"]({},e,{threadPointQueryRef:{parameters:c("IGDThreadDetailMainViewOffMsysQuery$Parameters"),variables:{min_uq_seq_id:c("IGDUqppSequenceIDTrackerSingleton").getSequenceID(),pass_message_list_gk:c("gkx")("3912"),thread_fbid:a.thread_fbid}}}));c("qex")._("4042")===!0&&(e=babelHelpers["extends"]({},e,{viewerSettingsQueryRef:{parameters:c("PolarisViewerSettingsQuery$Parameters"),variables:{}}}));return{entryPoints:{inboxTrayEntrypoint:d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("IGDInboxTray.entrypoint"),entryPointParams:{}})},queries:e}},root:c("JSResourceForInteraction")("PolarisDirectInboxRoot.react").__setRef("PolarisDirectInboxRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisDirectMessageRequestRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisDirectMessageRequestRoot.react").__setRef("PolarisDirectMessageRequestRoot.entrypoint")};g["default"]=a}),98);